package com.color_analysis_in_xinjiangtimes.push;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pushMessageDaoConfig;
    private final DaoConfig moreDaoConfig;

    private final PushMessageDao pushMessageDao;
    private final MoreDao moreDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pushMessageDaoConfig = daoConfigMap.get(PushMessageDao.class).clone();
        pushMessageDaoConfig.initIdentityScope(type);

        moreDaoConfig = daoConfigMap.get(MoreDao.class).clone();
        moreDaoConfig.initIdentityScope(type);

        pushMessageDao = new PushMessageDao(pushMessageDaoConfig, this);
        moreDao = new MoreDao(moreDaoConfig, this);

        registerDao(PushMessage.class, pushMessageDao);
        registerDao(More.class, moreDao);
    }
    
    public void clear() {
        pushMessageDaoConfig.getIdentityScope().clear();
        moreDaoConfig.getIdentityScope().clear();
    }

    public PushMessageDao getPushMessageDao() {
        return pushMessageDao;
    }

    public MoreDao getMoreDao() {
        return moreDao;
    }

}
